api/urls.py
from django.conf.urls import url

from . import views

app_name = 'api'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^cities/$', views.CityList.as_view()),
    url(r'^cities/(?P<pk>[0-9]+)/$', views.CityDetail.as_view()),
    url(r'^forecasts/$', views.ForecastList.as_view()),
    url(r'^forecasts/(?P<pk>[0-9]+)/$', views.ForecastDetail.as_view()),
]

app/urls.py
from __future__ import unicode_literals
from django.conf.urls import url
from django.core.urlresolvers import reverse

from . import views

app_name = 'app'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^register$', views.RegisterView.as_view(), name='register'),
    url(r'^login$', views.LoginView.as_view(), name='login'),
    url(r'^logout$', views.LogoutView.as_view(), name='logout'),
    url(r'^dashboard$', views.DashboardView.as_view(), name='dashboard'),
]

mysite/urls.py
"""imozulu URL Configuration
"""
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('app.urls')),
    url(r'^api/v1/', include('api.urls')),
]

app/models.py
from __future__ import unicode_literals
from passlib.hash import sha256_crypt

from django.db import models


class City(models.Model):
    name = models.CharField(max_length=255)
    # This is the cityId for fetching the city data from weather.news24.com
    code = models.CharField(max_length=255)

    class Meta:
        verbose_name = 'city'
        verbose_name_plural = 'cities'

    def __unicode__(self):
        return "{0} {1}".format(self.name, self.code)


class User(models.Model):
    city = models.ForeignKey(City, on_delete=models.SET_NULL, blank=True, null=True)
    email = models.EmailField(unique=True)
    password = models.CharField(max_length=255)

    def is_authentic(self, password):
        return sha256_crypt.verify(password, self.password)

    def __unicode__(self):
        return self.email


class Forecast(models.Model):
    city = models.ForeignKey(City, on_delete=models.CASCADE, related_name='forecasts')
    day = models.CharField(unique=True,max_length=255)
    description = models.CharField(max_length=255)
    sky_description = models.CharField(max_length=255, blank=True, null=True)
    precipitation_description = models.CharField(max_length=255, blank=True, null=True)
    precipitation_probability = models.IntegerField(blank=True, null=True)
    temperature_description = models.CharField(max_length=255, blank=True, null=True)
    temperature_high = models.IntegerField(blank=True, null=True)
    temperature_low = models.IntegerField(blank=True, null=True)
    uv_description = models.CharField(max_length=255, blank=True, null=True)
    air_description = models.CharField(max_length=255, blank=True, null=True)
    wind_speed = models.IntegerField(blank=True, null=True)
    wind_direction_description = models.CharField(max_length=255, blank=True, null=True)
    dew_point = models.CharField(max_length=255, blank=True, null=True)
    humidity = models.CharField(max_length=255, blank=True, null=True)
    comfort = models.CharField(max_length=255, blank=True, null=True)
    visibility = models.CharField(max_length=255, blank=True, null=True)
    rainfall = models.CharField(max_length=255, blank=True, null=True)
    snowfall = models.CharField(max_length=255, blank=True, null=True)
    icon_name = models.CharField(max_length=255, blank=True, null=True)
    beaufort_description = models.CharField(max_length=255, blank=True, null=True)

app/forms.py
from __future__ import unicode_literals
from passlib.hash import sha256_crypt
import re

from django import forms
from django.core.validators import RegexValidator


from . import models


TEL_REGEX = "^((?:\+27|27)|0)[\s-]?(\d{2})[\s-]?(\d{3})[\s-]?(\d{4})[\s]*$"


class RegisterForm(forms.ModelForm):
    password_repeat = forms.CharField(
            min_length=8, widget=forms.PasswordInput())

    class Meta:
        model = models.User
        fields = ['email', 'password']
        widgets = {
            'password': forms.PasswordInput(),
        }


    def clean_password(self):
        password = self.cleaned_data['password']
        return sha256_crypt.encrypt(password)

    def clean_password_repeat(self):
        password_repeat = self.cleaned_data['password_repeat']
        try:
            password = self.cleaned_data['password']
        except KeyError:
            raise forms.ValidationError('Password is required')

        if not sha256_crypt.verify(password_repeat, password):
            raise forms.ValidationError('Passwords must match')

        return password


class LoginForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(
            min_length=8, widget=forms.PasswordInput())

    def clean(self):
        cleaned_data = super(LoginForm, self).clean()
        email = cleaned_data.get('email')
        password = cleaned_data.get('password')

        if not password or not email:
            raise forms.ValidationError('All fields are required')

        error_msg = 'Problem with login, please check details and try again'
        try:
            user = models.User.objects.get(email=email)
        except:
            raise forms.ValidationError(error_msg)

        if not user.is_authentic(password):
            raise forms.ValidationError(error_msg)

api/views.py
from rest_framework import generics, permissions

from django.views.generic import TemplateView

from app import models as app_models

from . import serializers


class IndexView(TemplateView):
    template_name = 'api/index.html'


class CityList(generics.ListAPIView):
    queryset = app_models.City.objects.all()
    serializer_class = serializers.CitySerializer
    permission_classes = (permissions.IsAuthenticated,)


class CityDetail(generics.RetrieveAPIView):
    queryset = app_models.City.objects.all()
    serializer_class = serializers.CitySerializer
    permission_classes = (permissions.IsAuthenticated,)


class ForecastList(generics.ListCreateAPIView):
    queryset = app_models.Forecast.objects.all()
    serializer_class = serializers.ForecastSerializer
    permission_classes = (permissions.IsAuthenticated,)


class ForecastDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = app_models.Forecast.objects.all()
    serializer_class = serializers.ForecastSerializer
    permission_classes = (permissions.IsAuthenticated,)

app/views.py
from __future__ import unicode_literals
from django.conf import settings
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.views.generic import TemplateView, FormView
from django.views.generic.edit import CreateView
from django.views.generic.list import ListView
from django.http import HttpResponseRedirect

from . import forms
from . import models
from . import utils
from .log import logger


class IndexView(TemplateView):
    template_name = 'app/index.html'


class RegisterView(CreateView):
    template_name = 'app/register.html'
    form_class = forms.RegisterForm
    success_url = '/login'

    def form_valid(self, form):
        messages.add_message(
            self.request, messages.INFO, 'You have been registered, please login')
        return super(RegisterView, self).form_valid(form)


class LoginView(FormView):
    template_name = 'app/login.html'
    form_class = forms.LoginForm
    success_url = '/dashboard'

    def form_valid(self, form):
        self.request.session.set_expiry(0);
        email = form.cleaned_data['email']
        user = models.User.objects.filter(email=email).values()

        if user:
            logger.info("Logging in %s", user)
            self.request.session['user'] = dict(user[0])

        return super(LoginView, self).form_valid(form)


class LogoutView(TemplateView):

    def get(self, request, *args, **kwargs):
        logger.info("Logging out %s", self.request.user)
        self.request.session.flush();
        messages.add_message(request, messages.INFO, 'You have been logged out')
        return HttpResponseRedirect(reverse('app:index'))


class DashboardView(ListView):
    template_name = 'app/dashboard.html'
    paginate_by = 3

    @utils.require_login
    def get(self, request, *args, **kwargs):
        return super(DashboardView, self).get(request, *args, **kwargs)

    def get_queryset(self):
        user = models.User.objects.get(id=self.request.session['user']['id'])
        
        if user.city is None:
            code = settings.APP['default_city']['cityId']
        else:
            code = user.city.code
        logger.info("Retrieving forecast data for user: %s", user)
        queryset = models.Forecast.objects.filter(city__code=code)
        return queryset

api/templates/api/index.html
{% extends "app/base.html" %}

{% block content %}
    <div >
        <h1>MyWeatherSite API v1</h1>
    </div>
    <div class="list-group">
    <p>
        This is a simple API which authenticates via basic auth (for admins
        only) and provides just two end points.
    </p>
    <a href="#" class="list-group-item active">
        <h4 class="list-group-item-heading">Forecast End point</h4>
        <p class="list-group-item-text">/forecasts</p>
        <p class="list-group-item-text">/forecasts/pk</p>
        <p class="list-group-item-text">The pk is the primary key of a forecast.</p>
    </a>
    <a href="#" class="list-group-item active">
        <h4 class="list-group-item-heading">City End point</h4>
        <p class="list-group-item-text">/cities</p>
        <p class="list-group-item-text">/cities/pk</p>
        <p class="list-group-item-text">The pk is the primary key of a city.</p>
    </a>
    </div>
{% endblock %}

app/templates/app/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>WeatherApp</title>
        <link rel="stylesheet" href="{% static "app/css/bootstrap.min.css" %}">
        <link rel="stylesheet" href="{% static "app/css/styles.css" %}">
        {% block entrahead %}{% endblock %}
    </head>
    <body>
        <div class="container">
            <div class="content container-fluid">
                {% block message %}
                    {% if messages %}
                        {% for message in messages %}
                            <div class="message {% if message.tags %}{{ message.tags }}{% endif %}">
                                {{ message }}
                            </div>
                        {% endfor %}
                    {% endif %}
                {% endblock %}
                {% block content %}{% endblock %}
            </div>
        </div>
    </body>
</html>

app/templates/app/dashboard.html
{% extends "app/base.html" %}

{% block content %}
    <div class="header clearfix">
        <nav>
            <ul class="nav pull-right">
                <li role="presentation">
                    {%if request.session.user.email%}
                        <a href="{% url "app:logout" %}">Logout {{request.session.user.email}}</a>
                    {%else%}
                        <a href="{% url "app:login" %}">Login</a>
                    {%endif%}
                </li>
            </ul>
        </nav>
    </div>
    <div class="">
        {% for forecast in object_list %}
            <div class="panel panel-default">
                <div class="panel-heading">
                    <b>{{ forecast.day|date }}</b>
                </div>
                <div class="panel-body">
                    <p><i>{{ forecast.description }}</i></p>
                    <b>Temperatures:</b>
                    <span class="label label-danger">{{ forecast.temperature_high }}</span>
                    <span class="label label-info">{{ forecast.temperature_low }}</span>
                </div>
            </div>
        {% empty %}
            <div class="well well-lg">
                <i>We don't have any forecasts yet.</i>
            </div>
        {% endfor %}
    </div>
    {% if is_paginated %}
        <ul class="pagination pagination-lg">
            <li>
                {% if page_obj.has_previous %}
                    <a href="/dashboard?page={{ page_obj.previous_page_number }}" aria-label="Previous">previous</a>
                {% endif %}
                </a>
            </li>
            <li class="active">
                <a href="#">
                    {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
                </a>
            </li>
            {% if page_obj.has_next %}
                <li>
                    <a href="/dashboard?page={{ page_obj.next_page_number }}" aria-label="Next">next</a>
                </li>
            {% endif %}
        </ul>
    {% endif %}
{% endblock %}

app/templates/app/index.html
{% extends "app/base.html" %}

{% block content %}
    <div class="header clearfix">
        <nav>
            <ul class="nav pull-right">
                <li role="presentation">
                    {%if request.session.user.email%}
                        <a href="{% url "app:logout" %}">Logout {{request.session.user.email}}</a>
                    {%else%}
                        <a href="{% url "app:login" %}">Login</a>
                    {%endif%}
                </li>
            </ul>
        </nav>
    </div>
    <div class="jumbotron">
        <h1>WeatherApp</h1>
        <p class="lead">Get the latest weather forecast for the city you are interested in</p>
        <p><a class="btn btn-lg btn-success" href="{% url 'app:register' %}" role="button">Register now</a></p>
    </div>
{% endblock %}

app/templates/app/login.html
{% extends "app/base.html" %}
{% load widget_tweaks %}

{% block content %}
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">WeatherApp</a>
            </div>

            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{% url 'app:index' %}">Home</a></li>
                    <li><a href="{% url 'app:register' %}">Register</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="row">
        <div class="col-md-5">
            <form action="" method="post">
                {% csrf_token %}
                {% for field in form %}
                {% if field.errors %}
                <div class="form-group has-error">
                    <label class="control-label" for="id_{{ field.name }}">{{ field.label }}</label>
                    {{ field|attr:"class:form-control" }}
                    <span class="help-block">
                        {% for error in  field.errors %}{{ error }}{% endfor %}
                    </span>
                </div>
                {% else %}
                <div class="form-group">
                    <label class="control-label" for="id_{{ field.name }}">{{ field.label }}</label>
                    {{ field|attr:"class:form-control" }}
                    {% if field.help_text %}
                    <p class="help-block"><small>{{ field.help_text }}</small></p>
                    {% endif %}
                </div>
                {% endif %}
                {% endfor %}
                <input type="submit" class="btn btn-primary" value="Login" />
            </form>
        </div>
    </div>
{% endblock %}

app/templates/app/register.html
{% extends "app/base.html" %}
{% load widget_tweaks %}

{% block content %}
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">WeatherApp</a>
            </div>

            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{% url 'app:index' %}">Home</a></li>
                    <li><a href="{% url 'app:login' %}">Login</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="row">
        <div class="col-md-5">
            <form action="" method="post">
                {% csrf_token %}
                {% for field in form %}
                {% if field.errors %}
                <div class="form-group has-error">
                    <label class="control-label" for="id_{{ field.name }}">{{ field.label }}</label>
                    {{ field|attr:"class:form-control" }}
                    <span class="help-block">
                        {% for error in  field.errors %}{{ error }}{% endfor %}
                    </span>
                </div>
                {% else %}
                <div class="form-group">
                    <label class="control-label" for="id_{{ field.name }}">{{ field.label }}</label>
                    {{ field|attr:"class:form-control" }}
                    {% if field.help_text %}
                    <p class="help-block"><small>{{ field.help_text }}</small></p>
                    {% endif %}
                </div>
                {% endif %}
                {% endfor %}
                <input type="submit" class="btn btn-primary" value="Register" />
            </form>
        </div>
    </div>
{% endblock %}